name: Test and Deploy

on: [push, pull_request]
  
jobs:
  code-lint:
    name: lint using golangci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

  unit-test:
    name: unit test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.x
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: go test -race ./... -coverprofile=coverage.out -covermode=atomic
      
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
  
  deploy:
    name: deployment
    if: github.repository == 'indrasaputra/tetesan-hujan' && github.ref == 'refs/heads/deploy-to-heroku' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [unit-test, code-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: tetesan-hujan
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: cmd/bot
