name: Test

on: [push, pull_request]

jobs:
  unit-test:
    name: unit test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - run: go test -race ./... -coverprofile=coverage.out -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
